### ISSUE TITLE
Prevent dictionary lookup if einkbro not installed

### ISSUE THREAD

**Issue by gingerbeardman** [einkbro/askeinkbro#1]
I installed this in preparation of a tablet upgrade.

My current tablet is too old to run einkbro.

I noticed dictionary lookups fail if this plugin is enabled and einkbro is not installed.

The process halts at "searching dictionary"

**Comment by plateaukao** [comment]
if einkbro is not installed, there is no use for this plugin. You can just remove this plugin.

**Comment by gingerbeardman** [comment]
I disabled the plugin.

But it took me a while to figure out that this plugin was preventing proper operation of KOReader. Plugins should work in all scenarios and not do strange things.

Maybe the bug is from the AskGPT plugin that this plugin is based on?

**Comment by plateaukao** [comment]
i guess it's beacause  I asked it to launch EinkBro directly without checking if it's installed already.

**Comment by gingerbeardman** [comment]
But I do not even see the button or dictionary popup.

Video recording
https://imgur.com/a/S198k9Y

Hopefully you can see this is unexpected behaviour.

**Comment by gingerbeardman** [comment]
Bug has presented itself a slightly different way, on a device with einkbro installed.

Further information at: https://github.com/koreader/koreader/issues/10754

**Comment by gingerbeardman** [comment]
Fixed in #2
